jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8083
   servlet:
      context-path: /DNACrystalV2
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: 
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/DNACrystalV2?serverTimezone=UTC&useSSL=false
      username: root
      password: 
      hikari:
         poolName: pool
