jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8082
   servlet:
      context-path: /parqueadero
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/parqueadero
      username: ceiba
      password: ceiba
      hikari:
         poolName: pool
