package com.ceiba.modelo.util;


public enum EnumParametro {
	
	MONOLITICOS,
	LAMINADOS,
	DOBLE_ACRISTALAMIENTO,
	TEMPLADOS,
	FESTIVOS,
	HORA_ENTRADA,
	HORA_SALIDA,
	DIAS_MINIMOS_FECHA_COMPRA,
	DIAS_MAXIMOS_FECHA_COMPRA,
	MULTA_CANCELACION_COMPRA,
	MAXIMO_ANCHO_ITEM,
	MAXIMO_LARGO_ITEM,
	MAXIMO_ITEMS_POSIBLES,
	ITEMS_MINIMOS_DESCUENTO,
	DESCUENTO,
	RECARGO_FIN_SEMANA;
	
}
